-- 0014_ai_concierge.sql — the AI Inbox, and the concierge's route into the CRM.
--
-- The website's AI concierge answers visitors around the clock. Two things have
-- to survive the conversation:
--
--   1. The transcript. Every exchange is kept so the maison can read what was
--      actually said — what people ask for, what the agent got wrong, and what
--      was promised before a human picks the thread up. This is the AI Inbox.
--   2. The lead. When the visitor gives their details, the agent calls its
--      captureLead tool and the person lands in the CRM pipeline directly —
--      NOT in a triage queue. That is the deliberate difference from the other
--      two inboxes:
--
--        /contact  → inquiries      → promote by hand → leads (source='inquiry')
--        /atelier  → craft_requests → promote by hand → leads (source='craft')
--        AI chat   → leads (source='ai')            ← straight in
--
--      A visitor who has held a conversation and volunteered a phone number is
--      already further along than a form submission, and the agent only asks
--      once it judges them serious. Making a human re-promote that would just
--      be typing. The transcript stays attached either way.

-- ---------------------------------------------------------------------------
-- Conversations — one row per visitor session.
-- ---------------------------------------------------------------------------
create table if not exists public.ai_conversations (
  id               uuid primary key default gen_random_uuid(),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  -- Generated by the browser widget and sent with every message, so a refresh
  -- continues the same thread instead of opening a second one. Unique, because
  -- the route upserts on it.
  session_id       text not null unique,
  -- Filled in the moment captureLead fires. Null while the visitor is still
  -- anonymous — most conversations never get this far, and that is fine.
  visitor_name     text,
  visitor_phone    text,
  visitor_email    text,
  -- Why the agent thought they were worth capturing, in its own words. Gives
  -- the human picking this up the context without reading the whole transcript.
  qualification    text,
  lead_id          uuid references public.leads(id) on delete set null,
  status           text not null default 'new'
                     check (status in ('new', 'read', 'archived')),
  message_count    integer not null default 0,
  last_message_at  timestamptz,
  -- Which page they opened the chat on: a question from /shop is a different
  -- conversation from one started on /atelier.
  page_path        text,
  ip_hash          text,              -- salted hash of the client IP, never the raw address
  user_agent       text
);

create index if not exists ai_conversations_status_idx   on public.ai_conversations (status);
create index if not exists ai_conversations_recent_idx   on public.ai_conversations (last_message_at desc nulls last);
create index if not exists ai_conversations_lead_idx     on public.ai_conversations (lead_id);

drop trigger if exists ai_conversations_set_updated_at on public.ai_conversations;
create trigger ai_conversations_set_updated_at
  before update on public.ai_conversations
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Messages — the transcript itself, in order.
-- ---------------------------------------------------------------------------
create table if not exists public.ai_messages (
  id               uuid primary key default gen_random_uuid(),
  created_at       timestamptz not null default now(),
  conversation_id  uuid not null references public.ai_conversations(id) on delete cascade,
  role             text not null check (role in ('user', 'assistant')),
  content          text not null
);

-- The inbox always reads a whole thread oldest-first, so index the pair.
create index if not exists ai_messages_thread_idx on public.ai_messages (conversation_id, created_at);

-- ---------------------------------------------------------------------------
-- Row-level security. Same posture as every other public-facing table here:
-- the dashboard reads as `authenticated` behind is_admin(); the chat route
-- writes with the service role after validation and rate limiting. Nothing is
-- ever granted to anon — a transcript can contain a phone number.
-- ---------------------------------------------------------------------------
alter table public.ai_conversations enable row level security;
alter table public.ai_messages      enable row level security;

drop policy if exists "admins manage ai conversations" on public.ai_conversations;
create policy "admins manage ai conversations"
  on public.ai_conversations for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "admins manage ai messages" on public.ai_messages;
create policy "admins manage ai messages"
  on public.ai_messages for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

grant select, insert, update, delete on public.ai_conversations to authenticated;
grant select, insert, update, delete on public.ai_messages      to authenticated;
grant all on public.ai_conversations to service_role;
grant all on public.ai_messages      to service_role;

-- ---------------------------------------------------------------------------
-- Close the loop from leads: 'ai' joins the source vocabulary, and a lead
-- carries a link back to the conversation that produced it so the CRM card can
-- show what was said.
-- ---------------------------------------------------------------------------
alter table public.leads
  add column if not exists ai_conversation_id uuid references public.ai_conversations(id) on delete set null;

create index if not exists leads_ai_conversation_idx on public.leads (ai_conversation_id);

alter table public.leads drop constraint if exists leads_source_check;
alter table public.leads
  add constraint leads_source_check
  check (source in ('atelier', 'inquiry', 'manual', 'craft', 'ai'));
